export const INVENTORY_DROPDOWN_OPTIONS = {
  seasonality: [
    "Year Round",
    "Spring",
    "Summer",
    "Fall",
    "Winter",
    "Spring-Summer",
    "Summer-Fall",
    "Fall-Winter",
    "Holiday",
    "Limited Seasonal",
    "Special Order Only",
  ],
  availabilityStatus: [
    "In Stock",
    "Low Stock",
    "Out of Stock",
    "Preorder",
    "Special Order",
    "Discontinued",
    "Seasonal Only",
  ],
  qualityGrade: [
    { value: 1, label: "1 - Utility" },
    { value: 2, label: "2 - Standard" },
    { value: 3, label: "3 - Good" },
    { value: 4, label: "4 - Premium" },
    { value: 5, label: "5 - Luxury/Event" },
  ],
  colorFamily: [
    "White",
    "Ivory",
    "Cream",
    "Blush",
    "Pink",
    "Hot Pink",
    "Peach",
    "Coral",
    "Orange",
    "Yellow",
    "Green",
    "Lavender",
    "Purple",
    "Blue",
    "Burgundy",
    "Red",
    "Brown",
    "Chocolate",
    "Black",
    "Variegated",
    "Mixed",
  ],
  unitType: [
    "Stem",
    "Bunch",
    "Bundle",
    "Plant",
    "Pot",
    "Tray",
    "Box",
    "Case",
    "Garland",
    "Bouquet",
    "Arrangement",
    "Each",
  ],
  floralRole: [
    "Focal",
    "Line",
    "Filler",
    "Mass",
    "Accent",
    "Greenery",
    "Tropical",
    "Plant",
    "Supply/Accessory",
  ],
  bloomSize: ["Mini", "Small", "Medium", "Large", "Extra Large", "N/A"],
  stemLengthUnit: ["cm", "inches"],
  texture: [
    "Soft",
    "Delicate",
    "Airy",
    "Spiky",
    "Round",
    "Linear",
    "Glossy",
    "Matte",
    "Woody",
    "Wispy",
    "Dense",
    "N/A",
  ],
  storageTemperature: [
    "Room Temperature",
    "Cooler",
    "Tropical - Do Not Refrigerate",
    "Dry Storage",
    "Outdoor",
    "N/A",
  ],
  petToxicity: [
    "Unknown",
    "Generally Pet Safe",
    "Toxic to Cats",
    "Toxic to Dogs",
    "Toxic to Cats and Dogs",
    "Irritant",
  ],
  plantLightRequirement: [
    "Low Light",
    "Medium Indirect Light",
    "Bright Indirect Light",
    "Direct Sun",
    "Partial Shade",
    "N/A",
  ],
  plantWaterRequirement: [
    "Low",
    "Medium",
    "High",
    "Keep Moist",
    "Allow to Dry Between Watering",
    "N/A",
  ],
} as const;
