
ALTER TABLE public.flower_types ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT 'FLOWERS';
ALTER TABLE public.flower_types DROP CONSTRAINT IF EXISTS flower_types_name_key;
DROP INDEX IF EXISTS public.flower_types_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS flower_types_category_name_key ON public.flower_types (category, name);

WITH new_types(category, name, vase) AS (VALUES
 ('FLOWERS','Alstroemeria',10),('FLOWERS','Aster-Focal',7),('FLOWERS','Aster-Spray',7),
 ('FLOWERS','Bells of Ireland',7),('FLOWERS','Bouquets',5),('FLOWERS','Calla lily',10),
 ('FLOWERS','Carnations',14),('FLOWERS','Carnations-Mini',14),('FLOWERS','Combo Box',5),
 ('FLOWERS','Daffodil',5),('FLOWERS','Dahlia',5),('FLOWERS','Delphinium',7),
 ('FLOWERS','Gerbera',7),('FLOWERS','Gladiolus',7),('FLOWERS','Gypsophila',10),
 ('FLOWERS','Hydrangea',5),('FLOWERS','Hypericum',10),('FLOWERS','Iris',5),
 ('FLOWERS','Laceflower',7),('FLOWERS','Larkspur',7),('FLOWERS','Liatris',7),
 ('FLOWERS','Lilies',10),('FLOWERS','Limonium',14),('FLOWERS','Lisianthus',10),
 ('FLOWERS','Mums-Bunched',14),('FLOWERS','Mums-Stem',14),('FLOWERS','Novelty',7),
 ('FLOWERS','Peony',5),('FLOWERS','Pom Pons',14),('FLOWERS','Ranunculus',7),
 ('FLOWERS','Roses-Garden',5),('FLOWERS','Roses-Spray',7),('FLOWERS','Roses-Standard',7),
 ('FLOWERS','Roses-Sweetheart',7),('FLOWERS','Snapdragon',7),('FLOWERS','Statice',14),
 ('FLOWERS','Stock',7),('FLOWERS','Sunflower',7),('FLOWERS','Sweet Pea',5),
 ('FLOWERS','Tulips',5),('FLOWERS','Tulips-French',5),('FLOWERS','Waxflower',10),
 ('NOVELTY','Agapanthus',7),('NOVELTY','Ageratum',7),('NOVELTY','Alchemilla',7),
 ('NOVELTY','Allium',7),('NOVELTY','Amaranthus',7),('NOVELTY','Anemone',5),
 ('NOVELTY','Artemisia',7),('NOVELTY','Asclepias',7),('NOVELTY','Astilbe',5),
 ('NOVELTY','Astrantia',7),('NOVELTY','Berry',10),('NOVELTY','Branch',14),
 ('NOVELTY','Brunia',10),('NOVELTY','Bupleurum',7),('NOVELTY','Calendula',5),
 ('NOVELTY','Campanula',7),('NOVELTY','Clematis',5),('NOVELTY','Cornflower',5),
 ('NOVELTY','Cosmos',5),('NOVELTY','Craspedia',14),('NOVELTY','Daisy',7),
 ('NOVELTY','Dianthus',7),('NOVELTY','Dill',7),('NOVELTY','Euphorbia',7),
 ('NOVELTY','Fever Few',7),('NOVELTY','Foxglove',7),('NOVELTY','Freesia',7),
 ('NOVELTY','Geranium',7),('NOVELTY','Godetia',7),('NOVELTY','Grass',10),
 ('NOVELTY','Heather',10),('NOVELTY','Heliopsis',7),('NOVELTY','Helleborus',5),
 ('NOVELTY','Hyacinth',5),('NOVELTY','Kale/Brassic',10),('NOVELTY','Kangaroo Paw',10),
 ('NOVELTY','Lamb''s Ear',7),('NOVELTY','Lavender',10),('NOVELTY','Lilac',5),
 ('NOVELTY','Lysimachia',7),('NOVELTY','Mini Gerbera',7),('NOVELTY','Mint',7),
 ('NOVELTY','Misc.Fillers',7),('NOVELTY','Nigella',7),('NOVELTY','Ornithogalum',10),
 ('NOVELTY','Phlox',7),('NOVELTY','Pods',14),('NOVELTY','Poppy',5),
 ('NOVELTY','Poppy Mix',5),('NOVELTY','Rosemary',10),('NOVELTY','Rudbekia',7),
 ('NOVELTY','Rumex',7),('NOVELTY','Safflower',7),('NOVELTY','Sarracenia',10),
 ('NOVELTY','Scabiosa',5),('NOVELTY','Silene',7),('NOVELTY','Strawflower',14),
 ('NOVELTY','Thistle',10),('NOVELTY','Trachelium',7),('NOVELTY','Tuberose',7),
 ('NOVELTY','Tweedia',7),('NOVELTY','Veronica',7),('NOVELTY','Viburnum',5),
 ('NOVELTY','Yarrow',10),('NOVELTY','Zinnia',7),
 ('TROPICALS','Anthurium',14),('TROPICALS','Bird of Paradise',14),('TROPICALS','Bouquet',7),
 ('TROPICALS','Cymbidium',14),('TROPICALS','Gardenia',5),('TROPICALS','Ginger',14),
 ('TROPICALS','Heliconia',14),('TROPICALS','Leaves',14),('TROPICALS','Orchids',14),
 ('TROPICALS','Proteaceae',14),('TROPICALS','Stephanotis',7),('TROPICALS','Uluhe',14),
 ('GREENS','Aspidistra',14),('GREENS','Bear Grass',14),('GREENS','Bouquets',10),
 ('GREENS','Boxwood',14),('GREENS','Cedar Port Orford',14),('GREENS','Cocculus',14),
 ('GREENS','Emerald',14),('GREENS','Eucalyptus',14),('GREENS','Flat Fern',10),
 ('GREENS','Foxtail',14),('GREENS','Garlands',14),('GREENS','Huckleberry',14),
 ('GREENS','Ivy',10),('GREENS','Leatherleaf',14),('GREENS','Magnolia Foliage',14),
 ('GREENS','Ming Fern',14),('GREENS','Miscellaneous Greens',14),('GREENS','Monkey Grass',14),
 ('GREENS','Moss',30),('GREENS','Myrtle',14),('GREENS','Palm',14),
 ('GREENS','Papyrus',10),('GREENS','Pittosporum',14),('GREENS','Plumosus',14),
 ('GREENS','Rahmnus',14),('GREENS','Ruscus',14),('GREENS','Salal',14),
 ('GREENS','Smilax',10),('GREENS','Springeri',14),('GREENS','Sword Fern',14),
 ('GREENS','Tree Fern',14),('GREENS','Willow Curly',21),
 ('LIVE PLANTS','Accessories',90),('LIVE PLANTS','Aglaonema',90),('LIVE PLANTS','Azalea',30),
 ('LIVE PLANTS','Bromeliads',60),('LIVE PLANTS','Cactus and Succulents',180),
 ('LIVE PLANTS','Carnivorous Plants',60),('LIVE PLANTS','Dieffenbachia',90),
 ('LIVE PLANTS','Dish Gardens',60),('LIVE PLANTS','Dracaena',90),('LIVE PLANTS','Fern',60),
 ('LIVE PLANTS','Ficus',90),('LIVE PLANTS','Hanging Baskets',60),
 ('LIVE PLANTS','Hibiscus',60),('LIVE PLANTS','Hydrangea',30),('LIVE PLANTS','Ivy',60),
 ('LIVE PLANTS','Kalanchoe',45),('LIVE PLANTS','Misc. Flowering',45),
 ('LIVE PLANTS','Misc. Foliage',90),('LIVE PLANTS','Mum Plants',30),
 ('LIVE PLANTS','Orchid',60),('LIVE PLANTS','Palm',90),('LIVE PLANTS','Philodendron',90),
 ('LIVE PLANTS','Pothos',90),('LIVE PLANTS','Schefflera',90),
 ('LIVE PLANTS','Spathiphyllum',60),('LIVE PLANTS','Violets',45)
)
INSERT INTO public.flower_types (category, name, default_vase_life_days)
SELECT category, name, vase FROM new_types
ON CONFLICT (category, name) DO NOTHING;
